// Generated by: bun scripts/paw-art.mjs tests/fixtures/art/blip-bot.svg
// A mascot that is not the Paw, so the suite can prove the engine holds no
// opinion about the character it animates.
export const BLIP_ART = {
  head: "M150 60 C105 60 70 85 66 120 C62 150 64 185 76 205 C88 222 115 232 150 232 C185 232 212 222 224 205 C236 185 238 150 234 120 C230 85 195 60 150 60Z",
  earL: "M88 88 C70 80 52 60 46 36 C44 26 52 20 62 26 C78 36 90 58 94 76 C96 84 94 90 88 88Z",
  earR: "M212 88 C230 80 248 60 254 36 C256 26 248 20 238 26 C222 36 210 58 206 76 C204 84 206 90 212 88Z",
  cx: 150,
  cy: 146,
  unit: 85.87,
  pivotL: { x: 88, y: 88 },
  pivotR: { x: 212, y: 88 },
  eye: { cx: 123, cy: 141, w: 22, h: 34 },
  catch: { dx: -5, dy: -9, r: 2.2 },
  glass: {
    fill: "<radialGradient id=\"FILL\" cx=\"0\" cy=\"0\" r=\"1\" gradientUnits=\"userSpaceOnUse\" gradientTransform=\"%M% translate(130 80) rotate(90) scale(190 190)\"><stop offset=\"0\" stop-color=\"var(--fx-paw-glass-0, #3a2410)\" stop-opacity=\"0.92\"/><stop offset=\"0.55\" stop-color=\"var(--fx-paw-glass-1, #17100a)\" stop-opacity=\"0.98\"/><stop offset=\"1\" stop-color=\"var(--fx-paw-glass-2, #08050a)\"/></radialGradient>",
    rim: "<linearGradient id=\"RIM\" x1=\"50\" y1=\"30\" x2=\"250\" y2=\"230\" gradientUnits=\"userSpaceOnUse\" gradientTransform=\"%M%\"><stop offset=\"0\" stop-color=\"var(--fx-paw-rim-a, #fff6e8)\"/><stop offset=\"0.4\" stop-color=\"var(--fx-paw-rim-b, #ffcb7a)\"/><stop offset=\"0.75\" stop-color=\"var(--fx-paw-rim-c, #ff8a3d)\"/><stop offset=\"1\" stop-color=\"var(--fx-paw-rim-d, #ff5ea8)\"/></linearGradient>",
    defs: "<linearGradient id=\"D0\" x1=\"80\" y1=\"70\" x2=\"170\" y2=\"150\" gradientUnits=\"userSpaceOnUse\" gradientTransform=\"%M%\"><stop offset=\"0\" stop-color=\"#FFFFFF\" stop-opacity=\"0.30\"/><stop offset=\"0.35\" stop-color=\"#FFE9C4\" stop-opacity=\"0.09\"/><stop offset=\"1\" stop-color=\"#FFFFFF\" stop-opacity=\"0\"/></linearGradient><radialGradient id=\"D1\" cx=\"0\" cy=\"0\" r=\"1\" gradientUnits=\"userSpaceOnUse\" gradientTransform=\"%M% translate(150 232) rotate(90) scale(30 104)\"><stop offset=\"0\" stop-color=\"var(--fx-paw-floor-a, #ffcf94)\" stop-opacity=\"0.34\"/><stop offset=\"0.6\" stop-color=\"var(--fx-paw-floor-b, #ff8a3d)\" stop-opacity=\"0.14\"/><stop offset=\"1\" stop-color=\"var(--fx-paw-floor-c, #ff5ea8)\" stop-opacity=\"0\"/></radialGradient><filter id=\"D2\" x=\"-100%\" y=\"-100%\" width=\"300%\" height=\"300%\"><feGaussianBlur stdDeviation=\"9\"/></filter><filter id=\"D3\" x=\"-100%\" y=\"-100%\" width=\"300%\" height=\"300%\"><feGaussianBlur stdDeviation=\"4\"/></filter>",
    ground: "<ellipse cx=\"150\" cy=\"226\" rx=\"96\" ry=\"30\" fill=\"var(--fx-paw-halo, #ff9d4d)\" opacity=\"0.15\" filter=\"url(#D2)\"/><ellipse cx=\"150\" cy=\"232\" rx=\"84\" ry=\"15\" fill=\"url(#D1)\" filter=\"url(#D3)\"/>",
    sheen: "<path d=\"M84 104 C100 82 124 74 150 75 C174 76 194 84 208 96 C190 94 170 95 150 99 C126 104 104 112 82 124 C81 115 82 110 84 104Z\" fill=\"url(#D0)\"/><path d=\"M76 120 C82 96 96 78 116 68\" stroke=\"var(--fx-paw-glint, #FFFFFF)\" stroke-width=\"3.4\" stroke-linecap=\"round\" opacity=\"0.30\"/>"
  }
};
